import type { EntityConfig } from './index';

export const opcConfig: EntityConfig = {
  entityType: 'opc',
  label: 'One Person Company',
  itrForm: 'ITR-6',
  taxAuditForm: '3CA',
  nav: {
    journal: true, cashBook: true, pettyCash: true,
    purchaseRegister: 'conditional', salesRegister: 'conditional',
    purchaseReturns: 'conditional', salesReturns: 'conditional',
    billsReceivable: true, billsPayable: true,
    ledger: true, debtors: false, creditors: false, fixedAssets: false,
    investments: 'conditional', loans: 'conditional',
    trialBalance: true, tradingAccount: 'conditional',
    profitLoss: true, profitLossFormat: 'schedule_iii',
    plAppropriation: false, balanceSheet: true, balanceSheetFormat: 'schedule_iii',
    cashFlowStatement: 'conditional', fundsFlowStatement: 'never',
    incomeExpenditure: false, receiptsPayments: false,
    partnersCapital: false, revaluation: false, realisation: false,
    shareCapital: true, debentures: 'never', kartaCapital: false,
    fundAccounts: false, incompleteRecords: false, memberRegister: false,
    gst: 'conditional', incomeTax: true, tdsRegister: 'conditional',
    tcsRegister: 'conditional', advanceTax: true, deferredTax: true,
    brs: true, depreciation: false,
    audit: 'always', auditForm: '3CA',
    inventory: 'conditional', payroll: 'never',
    segmentReporting: false, relatedParty: true,
    accountingPolicies: true, asChecklist: true,
    fcra: 'never', applicationCheck: false, form10b: false, llpForms: false,
    ratioAnalysis: true, bsNotes: true, taxComputation: true, msmeDisclosure: true,
    contingentLiabilities: true, directorsReport: true, caro: true, costRecords: 'never', formN: false,
    salesInvoice: true, purchaseVoucher: true, paymentVoucher: true,
    receiptVoucher: true, debitNote: true, creditNote: true,
    bankImport: true,
  },
};
