import type { EntityConfig } from './index';

export const trustConfig: EntityConfig = {
  entityType: 'trust',
  label: 'Trust',
  itrForm: 'ITR-7',
  taxAuditForm: '10B',
  nav: {
    journal: true, cashBook: true, pettyCash: true,
    purchaseRegister: 'conditional', salesRegister: 'conditional',
    purchaseReturns: 'conditional', salesReturns: 'conditional',
    billsReceivable: true, billsPayable: true,
    ledger: true, debtors: false, creditors: false, fixedAssets: false,
    investments: 'conditional', loans: 'conditional',
    trialBalance: true, tradingAccount: 'never',
    profitLoss: false, profitLossFormat: 'traditional',
    plAppropriation: false, balanceSheet: true, balanceSheetFormat: 'traditional',
    cashFlowStatement: 'conditional', fundsFlowStatement: 'conditional',
    incomeExpenditure: true, receiptsPayments: true,
    partnersCapital: false, revaluation: false, realisation: false,
    shareCapital: false, debentures: 'conditional', kartaCapital: false,
    fundAccounts: true, incompleteRecords: false, memberRegister: false,
    gst: 'conditional', incomeTax: true, tdsRegister: 'conditional',
    tcsRegister: 'conditional', advanceTax: true, deferredTax: false,
    brs: true, depreciation: false,
    audit: 'conditional', auditForm: '10B',
    inventory: 'conditional', payroll: 'never',
    segmentReporting: false, relatedParty: true,
    accountingPolicies: true, asChecklist: true,
    fcra: 'conditional', applicationCheck: true, form10b: true, llpForms: false,
    ratioAnalysis: true, bsNotes: true, taxComputation: true, msmeDisclosure: true,
    contingentLiabilities: true, directorsReport: false, caro: false, costRecords: 'never', formN: false,
    salesInvoice: true, purchaseVoucher: true, paymentVoucher: true,
    receiptVoucher: true, debitNote: true, creditNote: true,
    bankImport: true,
  },
};
