-- ============================================================================
-- CA Studio — 0003_bank_import.sql
-- Bank import schema: import batches + parsed bank transactions.
--
-- Mirrors the offline-first localStorage store in
-- src/lib/bankImport/bankImportDb.ts (TS shapes: ImportBatch, BankTransaction).
-- Both tables are children of `companies` and follow the exact pattern from
-- 0001_core.sql: a denormalised `user_id` stamped by the existing
-- public.set_child_user_id() trigger, RLS enabled with a single for-all policy.
--
-- NOTE: store rows use STRING ids generated by the app (crypto.randomUUID()),
-- so the primary key `id` is TEXT (not uuid). `company_id` still references the
-- uuid companies.id (uuid-format strings coerce cleanly). Nested/derived-only
-- fields are none here; all columns are scalar.
--
-- Standalone, re-runnable DDL. Paste into Supabase → SQL Editor and run once.
-- ============================================================================

-- ============================================================================
-- 1. TABLES
-- ============================================================================

-- ── bank_import_batches ──────────────────────────────────────────────────────
-- Mirrors the TS `ImportBatch` interface: one row per imported statement file.
create table if not exists public.bank_import_batches (
  id           text primary key,               -- app-generated string id
  company_id   uuid not null references public.companies(id) on delete cascade,
  user_id      uuid not null,                  -- denormalised, set by trigger
  bank_account text not null default '',
  file_name    text not null default '',
  imported_at  timestamptz not null default now(),
  row_count    integer not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists bank_import_batches_company_idx
  on public.bank_import_batches (company_id);

-- ── bank_transactions ────────────────────────────────────────────────────────
-- Mirrors the TS `BankTransaction` interface: one row per statement line.
-- `import_batch` is the parent batch id (TEXT, matches bank_import_batches.id).
-- `journalized_id` is the journal entry id (app string id) once transferred.
create table if not exists public.bank_transactions (
  id             text primary key,             -- app-generated string id
  company_id     uuid not null references public.companies(id) on delete cascade,
  user_id        uuid not null,                -- denormalised, set by trigger
  import_batch   text not null,                -- parent batch id (batch_id)
  date           date not null,
  narration_raw  text not null default '',
  narration_clean text not null default '',
  payee          text not null default '',
  payment_mode   text not null default 'OTHER'
                   check (payment_mode in
                     ('UPI','NEFT','IMPS','RTGS','ATM','POS','CHQ','CASH','OTHER')),
  debit          numeric not null default 0,
  credit         numeric not null default 0,
  balance        numeric not null default 0,
  ref_no         text not null default '',
  journalized_id text,                          -- JE id once transferred (nullable)
  journalized_at timestamptz,                   -- ISO timestamp (nullable)
  created_at     timestamptz not null default now()
);
create index if not exists bank_transactions_company_idx
  on public.bank_transactions (company_id);
create index if not exists bank_transactions_batch_idx
  on public.bank_transactions (import_batch);

-- ============================================================================
-- 2. TRIGGERS — denormalised user_id stamping (reuses set_child_user_id)
-- ============================================================================
-- Prefixed "a_" so they sort/fire first (before the RLS WITH CHECK is evaluated),
-- exactly like the child-table triggers in 0001_core.sql.

drop trigger if exists a_bank_import_batches_set_user_id on public.bank_import_batches;
create trigger a_bank_import_batches_set_user_id
  before insert or update on public.bank_import_batches
  for each row execute function public.set_child_user_id();

drop trigger if exists a_bank_transactions_set_user_id on public.bank_transactions;
create trigger a_bank_transactions_set_user_id
  before insert or update on public.bank_transactions
  for each row execute function public.set_child_user_id();

-- ============================================================================
-- 3. ROW LEVEL SECURITY
-- ============================================================================

alter table public.bank_import_batches enable row level security;
alter table public.bank_transactions   enable row level security;

drop policy if exists bank_import_batches_all on public.bank_import_batches;
create policy bank_import_batches_all on public.bank_import_batches
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists bank_transactions_all on public.bank_transactions;
create policy bank_transactions_all on public.bank_transactions
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============================================================================
-- End of 0003_bank_import.sql
-- ============================================================================
