import type { DocumentMode, WizardModeConfig } from './types';
import type { CdnReason, Gstr1Table } from '@/lib/accounting/gstInvoices';

export const WIZARD_CONFIG: Record<DocumentMode, WizardModeConfig> = {
  sales_invoice: {
    title: 'Sales Invoice',
    partyLabel: 'Customer',
    accent: 'blue',
    accentBg: 'bg-blue-600',
    accentHover: 'hover:bg-blue-700',
    accentBadgeBg: 'bg-blue-100',
    accentBadgeText: 'text-blue-800',
    multiLineItems: true,
    showOriginalInvoice: false,
    showItc: false,
    showGstr1Badge: true,
    docType: 'TAX_INVOICE',
    isSalesMode: true,
  },
  purchase_invoice: {
    title: 'Purchase Invoice',
    partyLabel: 'Vendor',
    accent: 'emerald',
    accentBg: 'bg-emerald-600',
    accentHover: 'hover:bg-emerald-700',
    accentBadgeBg: 'bg-emerald-100',
    accentBadgeText: 'text-emerald-800',
    multiLineItems: false,
    showOriginalInvoice: false,
    showItc: true,
    showGstr1Badge: false,
    docType: 'TAX_INVOICE',
    isSalesMode: false,
  },
  sales_return: {
    title: 'Credit Note',
    partyLabel: 'Customer',
    accent: 'rose',
    accentBg: 'bg-rose-600',
    accentHover: 'hover:bg-rose-700',
    accentBadgeBg: 'bg-rose-100',
    accentBadgeText: 'text-rose-800',
    multiLineItems: true,
    showOriginalInvoice: true,
    showItc: false,
    showGstr1Badge: true,
    docType: 'CREDIT_NOTE',
    isSalesMode: true,
  },
  purchase_return: {
    title: 'Debit Note',
    partyLabel: 'Vendor',
    accent: 'amber',
    accentBg: 'bg-amber-600',
    accentHover: 'hover:bg-amber-700',
    accentBadgeBg: 'bg-amber-100',
    accentBadgeText: 'text-amber-800',
    multiLineItems: false,
    showOriginalInvoice: true,
    showItc: false,
    showGstr1Badge: false,
    docType: 'DEBIT_NOTE',
    isSalesMode: false,
  },
};

export const CDN_REASON_OPTIONS: Array<{ code: CdnReason; label: string }> = [
  { code: 'SALES_RETURN', label: 'Sales Return' },
  { code: 'PRICE_REDUCTION', label: 'Price Reduction' },
  { code: 'DEFICIENCY_SERVICE', label: 'Deficiency in Service' },
  { code: 'POST_SALE_DISCOUNT', label: 'Post-Sale Discount' },
  { code: 'CORRECTION', label: 'Correction' },
  { code: 'OTHER', label: 'Other' },
];

export const PURCHASE_RETURN_REASONS = [
  { code: 'DEFECTIVE', label: 'Defective Goods' },
  { code: 'WRONG_ITEM', label: 'Wrong Item Received' },
  { code: 'EXCESS_QTY', label: 'Excess Quantity' },
  { code: 'QUALITY', label: 'Quality Issue' },
  { code: 'PRICE_DIFF', label: 'Price Difference' },
  { code: 'OTHER', label: 'Other' },
];

export const GSTR1_TABLE_LABELS: Record<Gstr1Table, string> = {
  B2B: 'B2B — Table 4A',
  B2BA: 'B2BA — Table 9A',
  B2CL: 'B2CL — Table 5A',
  B2CS: 'B2CS — Table 7',
  B2CSA: 'B2CSA — Table 10',
  EXP: 'Export — Table 6A',
  EXPA: 'EXPA — Amended Exports',
  CDNR: 'CDNR — Table 9B',
  CDNRA: 'CDNRA — Amended CDNR',
  CDNUR: 'CDNUR — Table 9B',
  CDNURA: 'CDNURA — Amended CDNUR',
  NIL: 'Nil/Exempt — Table 8',
  AT: 'Advance Tax — Table 11A',
  ATA: 'ATA — Amended Advances',
  ATADJ: 'TXPD — Advance Adjustment',
  TXPDA: 'TXPDA — Amended',
  SEWP: 'SEZ with Payment — Table 6B',
  SEWOP: 'SEZ without Payment — Table 6C',
  DE: 'Deemed Export',
  NONE: 'Not in GSTR-1',
};

export const PURCHASE_BUCKETS: Array<{ code: string; label: string }> = [
  { code: 'B2B', label: 'B2B' },
  { code: 'URD', label: 'URD (Unregistered)' },
  { code: 'IMPG', label: 'IMPG (Import Goods)' },
  { code: 'IMPG_SEZ', label: 'IMPG-SEZ' },
  { code: 'IMPS', label: 'IMPS (Import Services)' },
  { code: 'ISD', label: 'ISD Credit' },
  { code: 'CDNR', label: 'CDNR (Supplier Note)' },
  { code: 'EXEMPT_NIL', label: 'Exempt / Nil / Non-GST' },
  { code: 'CAPITAL_GOODS', label: 'Capital Goods' },
];
